// CBoard settings
var settings = {
  preferredLanguage: 'cn' // en/cn: Switch language to Chinese
}

var CB_I18N = {
  "COMMON": {
    "OK": "确认",
    "LOAD": "加载",
    "CANCEL": "取消",
    "SAVE": "保存",
    "LOADING": "加载中...",
    "REFRESH": "刷新",
    "EDIT": "编辑",
    "DRAG": "拖拽",
    "BACK": "返回",
    "CONFIRM_DELETE": "真的想好了要删除吗?",
    "CONFIRM_SAVE_BEFORE_PREVIEW": "预览之前需要保存，确定保存？",
    "NOT_ALLOWED_TO_DELETE_BECAUSE_BE_DEPENDENT": "不允许删除，因为被依赖！",
    "TIP": "提示",
    "SUCCESS": "成功",
    "FAIL": "失败",
    "DEFAULT_CATEGORY": "默认分类",
    "NOT_EMPTY": "不能为空.",
    "NEW": "新建",
    "COPY": "复制",
    "DELETE": "删除",
    "EXPORT": "导出",
    "LOG": "日志",
    "LAST1M": "最近一月",
    "LAST1W": "最近一周",
    "LAST10D": "最近10天",
    "LAST10D_TIMESTAMP": "最近10天(时间戳)",
    "LAST3H_TIMESTAMP": "最近3小时(时间戳)",
    "LAST60MIN_TIMESTAMP": "最近60分钟(时间戳)",
    "FILTER_GROUP": "可选过滤",
    "SAVE_AS": "另存为",
    "PARAM": "条件",
    "DRILL_DOWN": "下钻",
    "ROLL_UP": "上卷",
    "WANRING": "警告！",
    "COLLAPSE": "最小化",
    "REMOVE": "关闭",
    "DATE": "日期",
    "VALUE": "值",
    "DEMAND": "提需求"
  },
  "TIPS": {
    "CAL_EXPR": "用于聚合后再计算. 使用上面的点击辅助输入避免输入错误. 如: Math.log(sum(columnA)/count(columB))"
  },
  "SIDEBAR": {
    "MENU": "菜单",
    "C_DASHBOARD": "看板",
    "MY_DASHBOARD": "我的看板",
    "CONFIG": "配置",
    "DATA_SOURCE": "数据源管理",
    "DATASET": "数据模型管理",
    "WIDGET": "图表设计",
    "CUBE": "数据模型",
    "DASHBOARD": "看板设计",
    "DASHBOARD_CATEGORY": "看板分类",
    "ADMIN": "管理",
    "USER_ADMIN": "用户管理",
    "RES_ADMIN": "资源管理",
    "JOB": "定时任务",
    "SHARE_RESOURCE": "资源分享",
    "NV": "新建页面",
    "CUBE_EDITABLE": "数据",
    "SCREEN_MENU": "大屏菜单",
    "STATISTICS": "统计",
    "DATASOURCE": "数据源"
  },
  "HEADER": {
    "SIGN_OUT": "注销",
    "TOGGLE_NAVIGATION": "切换导航",
    "CHANGE_PASSWORD": "修改密码",
    "CURRENT_PASSWORD": "当前密码",
    "NEW_PASSWORD": "新的密码",
    "CONFIRM_PASSWORD": "确认密码"
  },
  "FOOTER": {
    "COPYRIGHT": "",
    "VERSION": "版本"
  },
  "DASHBOARD": {
    "PARAM": {
      "NAME": "数据主题查询参数",
      "FIND": "查找",
      "OPT_VALUE": "值列表",
      "VALUE_LIST": "选定值列",
      "VALUE": "选定值",
      "VALUE_A": "下限",
      "VALUE_B": "上限",
      "SELECT_VALUE": "列表选值",
      "INPUT_VALUE": "输入值或表达式",
      "LIST_WARN": "值列表过大或者连续值，请不要加载数据列表!"
    }
  },
  "CONFIG": {
    "COMMON": {
      "CUSTOM_EXPRESSION": "可选表达式"
    },
    "DATA_SOURCE": {
      "DATA_SOURCE_HEADER": "数据源",
      "DATA_PROVIDER": "数据源类型",
      "NAME": "新建数据源名称",
      "TEST": "测试"
    },
    "WIDGET": {
      "MAX_COLOR": "最高颜色",
      "MIN_COLOR": "最低颜色",
      "CITY_MAX_RADIUS": "市最大半径",
      "CITY_MIN_RADIUS": "市最小半径",
      "IS_ENLARGE": "是否下钻放大",
      "ZOOM": "放大倍数",
      "SELECTOR": "选择条件",
      "CITYMAP": "2D区域地图",
      "ZONEMAP": "区域地图",
      "CHORD": "弦图",
      "WIDGET": "图表",
      "DATA_SOURCE": "数据源类型",
      "DATASET": "选择数据模型",
      "LOAD_DATA": "读取数据",
      "WIDGET_NAME": "图表名",
      "AXIS_NAME": "轴名",
      "CATEGORY": "图表分类",
      "WIDGET_TYPE": "图表类型",
      "CANCEL": "取消",
      "SAVE": "保存",
      "PREVIEW": "预览",
      "EXIST_QUERY": "已有查询",
      "NEW_QUERY": "新建查询",
      "SWITCH": "切换",
      "ROW": "列维",
      "GROUP": "行维",
      "VALUE": "指标",
      "MIN_VALUE": "最小值",
      "MAX_VALUE": "最大值",
      "VALUE_AXIS": "轴",
      "FILTER": "过滤",
      "THRESHOLD": "阈值",
      "LABEL": "名称",
      "FORMATTER": "格式化",
      "STYLE": "样式",
      "CHART": "图形",
      "ADD_NEW_AXIS": "添加轴",
      "ADD": "添加",
      "OPTIONAL": "可选",
      "ALIAS": "别名",
      "MORE": "更多",
      "EXAMPLE": "如",
      "FUNNEL": "漏斗图",
      "SANKEY": "桑基图",
      "CIRCULAR": "和弦图",
      "3DMAP": "三维地球",
      "3DBAR": "三维柱图",
      "3DAREA": "三维面图",
      "3DMAPLINE": "三维地球线图",
      "TABLE": "交叉表格",
      "DATALINETABLE": "表格",
      "CROSSTABLE": "下钻表格",
      "TREEGRID": "树状表格",
      "CROSSGREATTABLE": "下钻表格2",
      "FLEX": "灵活配置",
      "FLEX2": "灵活配置2",
      "GANTT": "甘特图",
      "KPI": "KPI",
      "PIE": "饼图",
      "PIE2": "饼图2",
      "flexChart": "flexChart",
      "flexD3Chart": "flexD3Chart",
      "LINE_BAR": "折线/柱状图",
      "LINE_BAR2": "折线/柱状图2",
      "LINE_BAR3": "折线/柱状图3",
      "SCATTER": "散点图/气泡图",
      "SCATTER2": "散点图",
      "MAP": "中国地图",
      "LINEMAP": "2D点线地图",
      "LINE": "折线",
      "LINE2": "折线",
      "LINE3": "折线",
      "ROSE": "玫瑰图",
      "FLEXD3CHART": "灵活配置D3",
      "BAR": "柱状",
      "STACKED_BAR": "堆叠柱状",
      "ONE_LINE_BAR": "一根线柱图",
      "WATER_FALL": "瀑布图",
      "AQUA": "蓝色",
      "RED": "红色",
      "YELLOW": "黄色",
      "GREEN": "绿色",
      "CYAN": "青色",
      "EXPRESSION": "表达式",
      "MEASURE": "指标列",
      "DIMENSION": "维度列",
      "ARITHMETIC": "运算",
      "COLUMN": "字段",
      "AGGREGATE": "聚合",
      "EXPRESSION_TEXT": "表达式",
      "CHECK": "校验",
      "FIND": "查找",
      "EQUAL": "等于",
      "NOT_EQUAL": "不等于",
      "HORIZONTAL": "垂直",
      "VERTICAL": "水平",
      "RADAR": "雷达图",
      "SHOW_BY_FILTER": "根据已有条件过滤",
      "TIPS_ROW_DIM": "行维",
      "TIPS_COLUMN_DIM": "列维",
      "TIPS_MEASURE": "值",
      "TIPS_DIM_NUM_0": "0",
      "TIPS_DIM_NUM_1": "1",
      "TIPS_DIM_NUM_0_MORE": "0个或多个",
      "TIPS_DIM_NUM_1_MORE": "1个或多个",
      "FROM_CACHE": "从缓存加载",
      "SIZE": "大小",
      "COLOR": "透明度",
      "PREVIEW_QUERY": "预览查询",
      "PERCENT_BAR": "百分比堆叠",
      "STACK_LINE": "堆叠面积图",
      "AGGREGATE_TYPE": "汇总类型",
      "GAUGE": "仪表",
      "ADD_NEW_STYLE": "添加样式",
      "LINE_STYLE": "线条样式",
      "STYLE_PROPORTION": "比例",
      "STYLE_COLOR": "颜色",
      "WORD_CLOUD": "标签云",
      "TREE_MAP": "矩形树图",
      "LEAF_DEPTH": "展示层级",
      "MULTI": "混合",
      "RANDOM": "随机",
      "BLUE": "蓝色",
      "PURPLE": "紫色",
      "AREA_MAP": "区域地图",
      "HEAT_MAP_CALENDER": "热点图（日历）",
      "DATE_FORMAT": "日期格式",
      "HEAT_MAP_TABLE": "热点图（表格）",
      "MARK_LINE_MAP": "标线地图(本地)",
      "LIQUID_FILL": "水球图",
      "STATIC": "静态",
      "DYNAMIC": "动态",
      "CIRCLE": "圆形",
      "PIN": "针形",
      "RECT": "矩形",
      "ARROW": "箭头形",
      "TRIANGLE": "三角形",
      "ROUND_RECT": "圆角矩形",
      "SQUARE": "正方形",
      "DIAMOND": "菱形",
      "BARPOLARSTACK": "环形柱图",
      "PIEPROPORTION": "百分比图",
      "BARLIMITS": "柱形范围图",
      "MULTI_LEVEL_PIE": "多层饼图",
      "CODEFLOWER": "多层饼图"
    },
    "DASHBOARD": {
      "DASHBOARD": "数据主题",
      "MY_DASHBOARD": "我的数据主题",
      "CATEGORY": "分类",
      "NAME": "名称",
      "ADD_ROW": "添加行",
      "ADD_COLUMN": "添加列",
      "ROW": "行",
      "HEIGHT": "行高度(像素)",
      "WIDTH": "宽度",
      "WIDGET": "图表",
      "PREVIEW": "预览",
      "ADD_PARAMROW": "添加参数行",
      "ADD_PARAM": "添加参数",
      "PARAM_ROW": "参数行",
      "PARAM": "查询参数",
      "PARAM_NAME": "参数名称",
      "CUBE_TREE": "数据主题中的数据模型/查询",
      "LINKED_COLUMN": "参数关联上的列",
      "PARAM_TYPE": "交互类型",
      "PARAM_TYPE_SELECTOR": "选择器",
      "PARAM_TYPE_SLIDER": "滑动器",
      "CHART_NAME": "图表名称",
      "ENTER_PARAMETER_NAME": "请输入参数名称",
      "DASHBOARD_SOMETHING_WRONG": "有部分图表访问出错,请检查数据主题的配置!",
      "VALUE_FORMMAT": "值格式化",
      "VIEW_FORMMAT": "显示格式化",
      "MIN": "最小值",
      "MAX": "最大值",
      "NOW": "现在",
      "ONE_HOUR_AGO": "一小时前",
      "ONE_DAY_AGO": "一天前",
      "ONE_MONTH_AGO": "一月前",
      "STEP": "步长",
      "MAX_RANGE": "最大间距",
      "DEFAUT_RANGE": "默认间距",
      "ONE_SECOND": "1秒种",
      "ONE_MINUT": "1分钟",
      "ONE_HOUR": "1小时",
      "ONE_DAY": "1天",
      "MAIN_NODE": "主节点",
      "SUB_NODE": "子节点",
      "ADD_MAIN_NODE": "添加主节点",
      "ADD_SUB_NODE": "添加子节点",
      "NODE_NAME": "节点名称",
      "TITLE": "标题",
      "NEW_GRID_LAYOUT": "新建网格布局",
      "NEW_TIMELINE_LAYOUT": "新建时间轴布局",
      "VALUE_FORMMAT_ALERT": "只有日期类型需要格式化",
      "AUTOMATIC_REFRESH_SWITCH": "自动刷新切换",
      "REMOVE_EMPTY_LINES": "清除空行",
      "DATA_REFRESH_TIME": "数据刷新时间"
    },
    "CATEGORY": {
      "NAME": "数据主题分类名称",
      "CATEGORY": "分类"
    },
    "DATASET": {
      "DATASET": "数据模型",
      "NAME": "名称",
      "CATEGORY": "分类",
      "LOAD_DATA": "读取数据",
      "DATASOURCE": "数据源",
      "ADD": "添加",
      "REAL_TIME_INTERVAL": "实时间隔(秒)",
      "REAL_TIME_TIP": "留空则不做后台刷新",
      "DIMENSION": "维度列",
      "HIERARCHY": "维度层级",
      "MEASURE": "指标列",
      "FILTER": "过滤器",
      "UNCLASSIFY": "未分类列",
      "TIP_EDIT_ALIAS": "编辑别名",
      "TIP_ADD_HIERARCHY": "添加层级",
      "TIP_SWITCH_TO_MEASURE": "转换为指标",
      "TIP_SWITCH_TO_DIMENSION": "转换为维度",
      "CUSTOM": "定制语句",
      "DEMAND": "需求制定",
      "EXPLAINATION": "解释"
    },
    "JOB": {
      "CONFIG": "配置",
      "JOB": "定时任务",
      "NAME": "名称",
      "TYPE": "类型",
      "LAST_EXEC_TIME": "最后执行时间",
      "EXEC_NOW": "立即执行",
      "ACTIVE_RANGE": "有效期",
      "MAIL": "邮件",
      "TO": "收件人",
      "CC": "抄送",
      "BCC": "密送",
      "SUBJECT": "主题",
      "ADD_DASHBOARD": "添加数据主题",
      "DASHBOARD": "数据主题",
      "EVERY": "每",
      "Minute": "分钟",
      "Hour": "小时",
      "Day": "天",
      "Week": "周",
      "Month": "月",
      "ON_THE": "的",
      "ON": "的",
      "OF": "的",
      "AT": "在",
      "PAST_THE_HOUR": "分",
      "USERNAME": "创建人",
      "FAIL": "失败",
      "FINISH": "完成",
      "PROCESSING": "处理中",
      "STATUS": "状态"
    },
    "SHARE_RES": {
      "YOUR_RES": "你的资源",
      "SHARE": "资源分享"
    }
  },
  "ADMIN": {
    "USER": {
      "USER": "用户管理",
      "LOGIN_NAME": "账号",
      "NAME": "姓名",
      "PASSWORD": "密码"
    },
    "ROLE": {
      "ROLE": "角色管理",
      "ROLE_NAME": "角色名",
      "ADMIN": "管理员"
    },
    "BOARD": "数据主题",
    "MENU": "菜单",
    "DATASOURCE": "数据源",
    "DATASET": "数据模型",
    "WIDGET": "图表",
    "JOB": "定时任务",
    "BRAIN_MAP": "脑图",
    "CONTACT_ADMIN": "请联系管理员申请以下权限",
    "BY_NAME": "按名称",
    "BY_ROLE": "按角色",
    "REVOKE": "撤销",
    "GRANT": "授予",
    "TOGGLE_UPDATE": "切换UDATE权限",
    "TOGGLE_DELETE": "切换DELETE权限"
  },
  "DATAPROVIDER": {
    "AGGREGATABLE_PROVIDER": "数据源聚合",
    "AGGREGATABLE_PROVIDER_SOLR": "数据源聚合(必须Solr5.0+)",
    "POOLEDCONNECTION": "是否使用连接池",
    "AIRFLOW": "连接算法编排",
    "JDBC": {
      "DRIVER": "驱动类 (如: com.mysql.jdbc.Driver)",
      "JDBCURL": "连接串 (如: jdbc:mysql://hostname:port/db)",
      "USERNAME": "数据库用户名",
      "PASSWORD": "数据库密码",
      "SQLTEXT": "查询语句"
    },
    "SAIKU": {},
    "TEXTFILE": {
      "BASE_PATH": "文件所在目录",
      "FILE_NAME": "文件名",
      "ENCODING": "编码",
      "SEPRATOR": "分隔符",
      "DATA_TYPE": "数据类型",
      "FIELD_NAMES": "字段名称",
      "QUOTE_CHAR": "引用字符",
      "ESCAPE_CHAR": "逃避字符"
    },
    "SOLR": {
      "SOLR_SERVERS": "Solr服务",
      "COLLECTION": "集合名称",
      "Q": "查询字段",
      "FQ": "过滤字段",
      "SORT": "排序字段",
      "START": "开始位置",
      "ROWS": "结果数",
      "FL": "结果字段"
    }
  },
  "NV": {
    "MENU": {
      "HOMEPAGE": "首页",
      "CUBE": "数据模型",
      "EXPLORE": "自助分析",
      "SHARE": "分享",
      "NEOVIS": "智慧图谱"
    },
    "COMMON": {},
    "DASHBOARD": {},
    "EXPLORE": {
      "FILTER": "过滤器",
      "INDEX": "指标",
      "ITEM": "配置项",
      "GRID": "图域",
      "LEGEND": "图例",
      "VAXIS": "值轴",
      "CAXIS": "类轴",
      "EXT": "选项",
      "CUSTOMIZE": "自定义",
      "TEXTPROMPT": "输入n%或一个整数",
      "TOP": "上",
      "BOTTOM": "下",
      "LEFT": "左",
      "RIGHT": "右",
      "CENTER": "中",
      "HORIZONTAL": "横",
      "VERTICAL": "纵",
      "ORIENT": "方向",
      "SHOWLEGEND": "显示图例",
      "INTERVAL": "间隔",
      "ROTATE": "旋转",
      "SHOWDATAZOOM": "显示时间缩放",
      "MARKPOINT": "显示柱状图头",
      "BARWIDTH": "柱宽",
      "LABEL": {
        "TOP": "柱头",
        "BOTTOM": "柱底",
        "OFFSET": {
          "TOP": "向上偏移",
          "BOTTOM": "向下偏移",
          "LEFT": "向左偏移",
          "RIGHT": "向右偏移"
        }
      },
      "FORM": "形态",
      "ANALYSIS": "自助分析",
      "CHART": "图表"
    }
  }
}

// $(function () {
//   angular.bootstrap($('html')[0], ['discovery'])
// })

// $.ajax({
//   url: 'i18n/' + settings.preferredLanguage + '/cboard.json',
//   type: 'GET',
//   dataType: 'json',
//   success: function (data) {
//     $(function () {
//       angular.bootstrap($('html')[0], ['discovery'])
//     })
//     return CB_I18N = data
//   },
//   async: false
// })

function getQueryString(name) {
  var regStr = "(^|&)" + name + "=([^&]*)(&|$)"
  var reg = new RegExp(regStr, "i")
  var r = window.location.search.substr(1).match(reg)
  if (r != null) return unescape(r[2])
  return null
}

// window.yiliToken = getQueryString('yili-token')
